### ISSUE TITLE
PHP Warning: Undefined array key "uid" in DataHandlerHook.php

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/sync_crop_areas#19]
Hi,

since version 2.2.0 I get a new error:
`PHP Warning: Undefined array key "uid" in /var/www/html/public/typo3conf/ext/sync_crop_areas/Classes/Hook/DataHandlerHook.php line 74`

**It only appears, when I add a new image and then try to save it. With existing images it works.**

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

I have just released version 2.2.1 to packagist and TER which solves that issue.
Thank you to make sync_crop_areas a better extension ;-)

Have a nice weekend.

PS: I will also release a new version 1.2.1 for TYPO3 9 and 10 (PHP < 7.4) within the next hour

Stefan
