### ISSUE TITLE
[DOC] Add composer code to readme + docs

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/sync_crop_areas#2]
docs + readme should have a `composer require jweiland/sync-crop-areas`.

Also add package name to t3o to have it there as well

**Comment by froemken** [comment]
Hello Georg,

I have updated the installation description in Docs and README:
https://github.com/jweiland-net/sync_crop_areas

Further I have added the packagist link to extensions.typo3.org

Thank you for your help

Stefan
