### ISSUE TITLE
Cropping of custom records will not work anymore

### ISSUE THREAD

**Issue by KlickUndKlar** [jweiland-net/sync_crop_areas#22]
TYPO3 Version: 10.4.25
Extension Version: 2.2.1
Bootstrap Package Version: 11.0.3

Since last update of your extension, the SysFileReference in custom records (like Cards of BootstrapPackage) is broken. 

- The already set aspect ratio is lost
- Thumbs are not generated anymore
- Some cropping variants are missing
- Frontend rendering of images is broken

See Screenshot

<img width="679" alt="Bildschirmfoto 2022-03-02 um 16 54 44" src="https://user-images.githubusercontent.com/25507655/156398528-3265aece-a7ef-4e4f-af19-6c8aee39af5e.png">

Included like described in documentation.

https://docs.typo3.org/p/jweiland/sync-crop-areas/main/en-us/KnownProblems/Index.html

**Comment by froemken** [comment]
Hello @KlickUndKlar 

thank you for your help to make sync_crop_areas a better extension.

EXT:sync_crop_areas just adds one Checkbox in BE form and registers a Hook. Nothing more. So all magic happens while saving a record. So, if images and CropVariants are not displayed in BE form correctly, it's not a problem of sync_crop_areas.

I have just installed bootstrap ^11 for TYPO3 10.4.25 and sync_crop_areas 2.2.1. I'm working here with 7 CropVariants configured by TCA and overridden with PageTsConfig.

I've created a new file in [site_apckage]/Configuration/TCA/tx_bootstrappackage_card_group_item.php

```
<?php
if (!defined('TYPO3_MODE')) {
    die('Access denied.');
}

call_user_func(static function () {
    // Only needed, if foreign extension author does not use
    // "imageoverlayPalette" palette from core.
    // Example for bootstrap table "tx_bootstrappackage_card_group_item":
    $table = 'tx_bootstrappackage_card_group_item';
    $columns = ['image'];
    $imgFileType = \TYPO3\CMS\Core\Resource\File::FILETYPE_IMAGE;

    if (isset($GLOBALS['TCA'][$table]['columns'])) {
        foreach ($columns as $column) {
            if (isset($GLOBALS['TCA'][$table]['columns'][$column]['config'])) {
                $imgConfig = $GLOBALS['TCA'][$table]['columns'][$column]['config'];
                if (isset($imgConfig['overrideChildTca']['types'][$imgFileType]['showitem'])) {
                    // Add column "sync_crop_areas" before "crop" column
                    $imgConfig['overrideChildTca']['types'][$imgFileType]['showitem'] = str_replace(
                        'crop',
                        'sync_crop_area, crop',
                        $imgConfig['overrideChildTca']['types'][$imgFileType]['showitem']
                    );
                    $GLOBALS['TCA'][$table]['columns'][$column]['config'] = $imgConfig;
                }
            }
        }
    }
});
```

Now I have created a new content element of type `card_group` and added 2 new cards with an image and it works like expected.

It seems that you have a problem with imagemagick or graphicsmagick. Maybe a miss-configuration, a missing `,` somewhere which breaks the BE form compiling. But, sorry, I can't confirm your issue.

Please provide further data, PHP, configuration, but for now I will close this issue.

Nice greetings

Stefan

**Comment by KlickUndKlar** [comment]
Hi Stefan

Thanks for your investigations! It really looks like our TYPO3 Instance has a problem. So we will search on our side for a misconfiguration or other reasons. 

Greets 

Ben
