### ISSUE TITLE
Default setting od sys_file_reference changeable?

### ISSUE THREAD

**Issue by blueamerican** [jweiland-net/sync_crop_areas#23]
It would be great, if i can change the default setting to 0.

If i do this, i get an error in the BE.

`TCEFORM.sys_file_reference.sync_crop_area = 0`

**Comment by froemken** [comment]
Hello @blueamerican 

The default value in SQL and TCA are not overwriteable with PageTSconfig:
https://docs.typo3.org/m/typo3/reference-tsconfig/11.5/en-us/PageTsconfig/TceForm.html#config
(see black table. "default" is not listed).

So, if you want to disable that field by default, you have to create a new PHP file in your SitePackage extension:

`[yourExt]/Configuration/TCA/Overrides/sys_file_reference.php`

Add or update following:

```
<?php
$GLOBALS['TCA']['sys_file_reference']['columns']['sync_crop_area']['config']['default'] = 0;
```

Clear system cache.

Have a nice start into the upcoming weekend

Stefan

**Comment by sfroemkenjw** [comment]
Hello @blueamerican 

please use TCADefaults: https://docs.typo3.org/m/typo3/reference-tsconfig/11.5/en-us/PageTsconfig/TcaDefaults.html

In that case you can set the default for new relations

Stefan
