### ISSUE TITLE
sync_crop_areas for bootstrap_package - example not syncing?

### ISSUE THREAD

**Issue by mdlrvie** [jweiland-net/sync_crop_areas#24]
Great and very useful extension, which should be part of core functions. 

Tested environment:
TYPO3 11.5.23, bootstrap_package 12.0.7

I follwed your example: 
https://docs.typo3.org/p/jweiland/sync-crop-areas/main/en-us/KnownProblems/Index.html
... the sync-switch appears in the user interface of TYPO3 Backend (tx_bootstrappackage_card_group_item), but on save nothing happens. The core tables (tt_content, pages) does that perfect.

**Comment by sfroemkenjw** [comment]
Hello @mdlrvie 

thank you for your bug report. I can confirm this issue. Seems something has changed within the bootstrap package. I have adopted that change and released a new version 2.2.3 to TER.

Stefan
