### ISSUE TITLE
Simplify ext_emconf

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/sync_crop_areas#3]
According to https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/DeclarationFile/Index.html most properties can be removed

additionally the comment stating that the ext_emconf has been created 2013 looks strange

**Comment by froemken** [comment]
Hello Georg,

thank you for that link. Seems that I have looked into the Documentation since...äh...since 2013 :-)

I have removed many of the options from ext_emconf.php

Thank you for making sync_crop_areas much better.

Stefan
