### ISSUE TITLE
Warning: The TYPO3 extension package "jweiland/sync-crop-areas", does not define an extension key in its composer.json.

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/sync_crop_areas#7]
`The TYPO3 extension package "jweiland/sync-crop-areas", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)
`

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

thank you for reporting this issue. I have added extKey already in dev-master.
I thought with next feature or bugfix we will release a new version.

But for you I just have released a new version 1.0.3.
Have fun having one less warning in composer ;-)

Stefan

**Comment by PhilippKuhlmay** [comment]
Top thanks.
