### ISSUE TITLE
How to add sync_crop_areas to custom content elements?

### ISSUE THREAD

**Issue by Treupo** [jweiland-net/sync_crop_areas#8]
I have a (custom) content element. Card Group from the EXT:bootstrap_package. I'd like to have the sync_crop_areas function there too. Is it somehow possible? Do I have to override the TCA for this element by myself?
Thank's in advance.

**Comment by PhilippKuhlmay** [comment]
Hi 
I use a content element from the bootstrap package called "card group". There I don't habe the switch for synchronizing the crop areas. I was wondering how to add it to this content element.

> If your content element is using the public API for file relations our sync_crop_areas will also work for your element.
So the issue is not in this extension, but in the bootstrap package?

Philipp

**Comment by froemken** [comment]
Hello @Treupo @PhilippKuhlmay 

thank you for the hint "card group". That helps me a lot understanding your problem in more detail. The bootstrap_package does not use the default palette of columns to show cropping feature.

I have added a new section into documentation of sync_crop_areas why this is a problem and how to solve that:

https://github.com/jweiland-net/sync_crop_areas/blob/master/Documentation/KnownProblems/Index.rst#sync_crop_areas-does-not-work-for-columns-of-extension-xy

I can't add that feature to sync_crop_areas as I have to be sure that my extension MUST BE loaded AFTER all other extensions and that is nearly impossible. So you have to add these lines of code into your site_package extensions
